language: ruby
cache: bundler
env:
  global:
  - WASH_VERSION=0.17.0
before_script:
- curl -sfL https://github.com/puppetlabs/wash/releases/download/${WASH_VERSION}/wash-${WASH_VERSION}-x86_64-unknown-linux.tgz | tar -xzC ~/bin
# TODO: setup some targets in docker for Bolt to connect to
script:
# TODO: create a bolt inventory file
- wash validate ./bolt
