language: ruby
cache: bundler
services:
- docker
env:
  global:
  - WASH_VERSION=0.19.0
before_script:
- curl -sfL https://github.com/puppetlabs/wash/releases/download/${WASH_VERSION}/wash-${WASH_VERSION}-x86_64-unknown-linux.tgz | tar -xzC ~/bin
# Run a custom Dockerfile with locale and several users for testing
- docker build spec -t sshd
- docker run -d -p 22 --name test_sshd sshd
script:
- PORT=$(docker port test_sshd 22 | cut -f2 -d:)
- echo 'Building user Bolt v1 inventory'
- mkdir -p ~/.puppetlabs/bolt
- touch ~/.puppetlabs/bolt/bolt.yaml
- |
  cat << EOF > ~/.puppetlabs/bolt/inventory.yaml
  version: 1
  nodes:
  - name: localhost
    config:
      transport: ssh
      ssh:
        port: ${PORT}
        user: root
        password: root
        host-key-check: false
  EOF
- echo 'Validate with user Boltdir'
- wash validate ./bolt
- echo 'Building local Bolt v2 inventory'
- touch bolt.yaml
- |
  cat << EOF > inventory.yaml
  version: 2
  targets:
  - uri: localhost
    config:
      transport: ssh
      ssh:
        port: ${PORT}
        user: root
        password: root
        host-key-check: false
  EOF
- echo 'Validate with local Boltdir'
- CWD=$(pwd)
- |
  cat << EOF > wash.yaml
  external-plugins:
  - script: ${CWD}/bolt
  bolt:
    dir: ${CWD}
  EOF
- wash validate bolt --config-file wash.yaml
